---
# AAP 2.7 Default execution environment plus infra.aap_configuration.
# Its dependencies are already in the base image, so only Galaxy is needed.
version: 3

images:
  base_image:
    # yamllint disable-line rule:line-length
    name: registry.redhat.io/ansible-automation-platform-27/ee-supported-rhel9:latest

dependencies:
  galaxy: requirements.yml

# options:
  # package_manager_path: /usr/bin/microdnf
