apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  extra_settings:
    - setting: "REDIRECT_IS_HTTPS"
      value: '"True"'
  redis_mode: "cluster"
  route_tls_termination_mechanism: edge
  service_type: clusterip
  image_pull_policy: IfNotPresent
  ingress_type: route
  no_log: true
  mcp:
    disabled: true
  database:
    resource_requirements:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 800Mi
    storage_requirements:
      requests:
        storage: 50Gi
  api:
    log_level: INFO
    replicas: 1
    resource_reqeuirements:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "300m"
        memory: "1Gi"
  controller:
    replicas: 3
    extra_settings:
      - setting: "ALLOW_LOCAL_RESOURCE_ACCESS"
        value: "True"
    ee_resource_requirements:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "300m"
        memory: "1Gi"
    redis_resource_requirements:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "300m"
        memory: "1Gi"
    rsyslog_resource_requirements:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "300m"
        memory: "1Gi"
    task_resource_requirements:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "300m"
        memory: "0.8Gi"
    web_resource_requirements:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "300m"
        memory: "0.8Gi"
  eda:
    api:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "0.8Gi"
    event_stream:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "0.8Gi"
    redis:
      resource_reqeuirements:
        limits:
          cpu: "1"
          memory: "0.8Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
    scheduler:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
    ui:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
    worker:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
  hub:
    storage_type: S3
    object_storage_s3_secret: s3-credentials
    api:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
    content:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
    resource_reqeuirements:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "300m"
        memory: "1Gi"
    web:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
    worker:
      resource_reqeuirements:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
    lightspeed:
      disabled: true
    redis:
      replicas: 1
      resource_reqeuirements:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"